
"use client"

import { useState, useEffect } from "react"
import { ExpenseForm } from "@/components/expense/expense-form"
import { SummaryDashboard } from "@/components/expense/summary-dashboard"
import { ExpenseList } from "@/components/expense/expense-list"
import { Expense, ExpenseCategory } from "@/app/lib/types"
import { expenseService } from "@/app/lib/expense-service"
import { ShieldCheck, Wallet } from "lucide-react"

export default function SpendWiseDashboard() {
  const [expenses, setExpenses] = useState<Expense[]>([])
  const [isLoaded, setIsLoaded] = useState(false)

  useEffect(() => {
    setExpenses(expenseService.getExpenses())
    setIsLoaded(true)
  }, [])

  const handleAddExpense = (newExpenseData: { amount: number; description: string; date: string; category: ExpenseCategory }) => {
    const created = expenseService.addExpense(newExpenseData)
    setExpenses(prev => [created, ...prev])
  }

  const handleDeleteExpense = (id: string) => {
    expenseService.deleteExpense(id)
    setExpenses(prev => prev.filter(e => e.id !== id))
  }

  const handleExport = async () => {
    if (expenses.length === 0) return
    
    try {
      const { jsPDF } = await import('jspdf')
      const { default: autoTable } = await import('jspdf-autotable')
      
      const doc = new jsPDF()
      
      doc.setFontSize(18)
      doc.text("SpendWise Expense Report", 14, 20)
      
      doc.setFontSize(10)
      doc.setTextColor(100)
      doc.text(`Generated by: Crisostomo, L. IT3A`, 14, 28)
      doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 34)
      
      const tableData = expenses.map(e => [
        new Date(e.date).toLocaleDateString(),
        e.description,
        e.category,
        `₱${e.amount.toFixed(2)}`
      ])
      
      autoTable(doc, {
        startY: 40,
        head: [['Date', 'Description', 'Category', 'Amount']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: [37, 99, 235] },
      })
      
      doc.save(`spendwise_report_${new Date().toISOString().split('T')[0]}.pdf`)
    } catch (error) {
      console.error("Failed to generate PDF", error)
    }
  }

  if (!isLoaded) return null

  return (
    <main className="max-w-5xl mx-auto px-4 py-12 md:py-20">
      <header className="mb-12 text-center">
        <div className="flex items-center justify-center gap-2 mb-3">
          <div className="w-10 h-10 bg-primary rounded-xl flex items-center justify-center shadow-lg shadow-primary/20">
            <Wallet className="text-primary-foreground w-6 h-6" />
          </div>
          <h1 className="text-3xl font-headline font-bold text-foreground">Daily Expense Tracker</h1>
        </div>
        <p className="text-muted-foreground flex items-center justify-center gap-2 text-sm">
          <ShieldCheck className="w-4 h-4 text-accent" />
          Professional Expense Management with AI Categorization
        </p>
      </header>

      <div className="grid grid-cols-1 gap-10">
        <section className="max-w-2xl mx-auto w-full">
          <ExpenseForm onSuccess={handleAddExpense} />
        </section>

        <section className="space-y-8">
          <div className="flex flex-col gap-2">
            <h2 className="text-2xl font-headline font-semibold text-primary">Overview</h2>
            <div className="h-1 w-20 bg-accent rounded-full"></div>
          </div>
          <SummaryDashboard expenses={expenses} />
        </section>

        <section className="space-y-8">
          <ExpenseList 
            expenses={expenses} 
            onDelete={handleDeleteExpense} 
            onExport={handleExport}
          />
        </section>
      </div>

      <footer className="mt-20 pt-8 border-t text-center text-xs text-muted-foreground">
        <p>© Crisostomo, L. IT3A</p>
      </footer>
    </main>
  )
}
